<<<<<<< HEAD
version: 1
accounts:
  - name: alice
    coins: ["1000token", "100000000stake"]
  - name: bob
    coins: ["500token"]
validator:
  name: alice
  staked: "100000000stake"
client:
  vuex:
    path: "client"
=======
accounts:
  - name: alice
    coins: ["10000000000uzen"]
  - name: bob
    coins: ["5000000000uzen"]
validator:
  name: alice
  staked: "100000000uzen"
client:
  vuex:
    path: "vue/src/store"
faucet:
  name: bob 
  coins: ["50000000uzen"]
genesis:
  app_state:
    crisis: 
      constant_fee:
        denom: "uzen"
    gov: 
      deposit_params: 
          max_deposit_period: "172800s"
          min_deposit: 
            - amount: "1000000"
              denom: "uzen"
    staking:
      params:
        bond_denom: "uzen"
    mint:
      params:
        mint_denom: "uzen"
    token: 
      params: 
        token_tax_rate: "0.400000000000000000"
        issue_token_base_fee: 
          denom: "zen"
          amount: "1000"
        mint_token_fee_ratio: "0.100000000000000000"
    

      
>>>>>>> d5ca49900ba5c120e365148b35ab8d6debdfe88d
